#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <string>

#define CONST_STR(NAME) constexpr char NAME[]

namespace EpyGen {
    CONST_STR(VERSION) = "EpyGen v1.0";

    CONST_STR(CPP_HEADER) = "/*\n \
 * This file was automatically generated by %s on %s.\n \
 *  Do not modify this file unless you know what you are doing.\n \
 *\n \
 */\n \
#include <Python.h>\n \
#include <stdexcept>\n \
#include <exception>\n";

}

#endif

